name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push tag for released action
        run: |
          echo "hello world"
          bash build.sh
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        release_name: ${{ steps.vars.outputs.tag }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/kicad-eurorack-library-${{ steps.vars.outputs.tag }}.zip
        asset_name: kicad-eurorack-library-${{ steps.vars.outputs.tag }}.zip
        asset_content_type: application/zip

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/kicad-eurorack-tools-${{ steps.vars.outputs.tag }}.zip
        asset_name: kicad-eurorack-tools-${{ steps.vars.outputs.tag }}.zip
        asset_content_type: application/zip

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/kicad-eurorack-simluation-${{ steps.vars.outputs.tag }}.lib
        asset_name: kicad-eurorack-simluation-${{ steps.vars.outputs.tag }}.lib
        asset_content_type: application/text

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
